# -*- coding: utf-8 -*-
"""Dicas alternativas para as 250 palavras mais frequentes do banco.

Cada palavra tem 2 dicas adicionais (a 1ª já existe no words_pt.py).
Estilo Coquetel: curtas (até ~40 chars), sem repetir a palavra.

Gerado em sessão v11.1 — 250 palavras × 2 dicas = 500 dicas novas.
"""

ALT_CLUES = {
    # ─── 3 letras (105 palavras) ─────────────────────────────────────
    'OLA': ['Cumprimento amigável', 'Como se diz "hi" em português'],
    'RAP': ['Estilo do Eminem', 'Música falada e ritmada'],
    'IMA': ['Atrai metais ferrosos', 'Preso na geladeira'],
    'ORO': ['Metal precioso (esp.)', 'Cor do sol em espanhol'],
    'LAR': ['Aconchego do lado da família', 'Doce ___ doce'],
    'ARO': ['Borda da roda', 'Brinco circular'],
    'ARA': ['Papagaio grande e colorido', 'Ave da Amazônia'],
    'ALO': ['Atendendo o telefone', 'Cumprimento por celular'],
    'AMA': ['Quer bem', 'Babá em Portugal'],
    'AVE': ['Animal com penas', 'Saudação latina antiga'],
    'OPA': ['Espanto leve', 'Quase caí!'],
    'ETA': ['Interjeição mineira', 'Letra grega Η'],
    'CAL': ['Material de cimentar', 'Branco da parede'],
    'ALA': ['Setor de um prédio', 'Lateral em esportes'],
    'UPA': ['Pegar no colo', 'Subindo o nenê'],
    'ASA': ['Permite o voo da ave', 'Capital do Brasil (abrev.)'],
    'UNO': ['Jogo do amarelinho', 'Um, em italiano'],
    'ATA': ['Documento de reunião', 'Fruta também chamada pinha'],
    'FIA': ['Trabalha no tear', 'Quem ___ os fios'],
    'NOS': ['1ª pessoa do plural', 'Plural de nó'],
    'EIS': ['Veja só!', 'Apresentando algo'],
    'ROM': ['Memória de leitura', 'Cidade italiana (ingl.)'],
    'ROL': ['Catálogo de itens', 'Listagem'],
    'GRA': ['Bago de cereal', 'Semente'],
    'MAR': ['Onde nada o peixe', 'Atlântico ou Pacífico'],
    'MAE': ['Quem dá à luz', 'Dia das ___'],
    'COR': ['Vermelho, azul, verde...', 'Pigmento'],
    'AVO': ['Pai do pai', 'Patriarca da família'],
    'RIR': ['Soltar gargalhadas', 'Achar graça'],
    'RPM': ['Velocidade do motor', 'Rotações por minuto (sigla)'],
    'ECA': ['Que nojo!', 'Reação a algo asqueroso'],
    'RUA': ['Logradouro público', 'Calçada e asfalto'],
    'ECO': ['Som que volta', 'Reverberação'],
    'DOR': ['Pancada machuca, dá ___', 'Doi muito'],
    'PAN': ['Prefixo de "todos"', 'Mitologia grega: deus dos bosques'],
    'TAI': ['Povo do Sudeste Asiático', 'Idioma de Bangkok'],
    'SOL': ['Astro-rei', 'Brilha durante o dia'],
    'OVO': ['Posto pela galinha', 'Cozido, frito ou mexido'],
    'SER': ['Verbo de existência', 'Ente, criatura'],
    'SPA': ['Sauna e massagem', 'Local de relaxamento'],
    'APA': ['Reserva ambiental (sigla)', 'Sigla ecológica'],
    'SAL': ['Cloreto de sódio', 'Vai com a pipoca'],
    'UFA': ['Que cansaço!', 'Alívio depois do susto'],
    'MUS': ['Jogo de cartas espanhol', 'Quatro jogadores em duplas'],
    'VAN': ['Transporte escolar comum', 'Carro de 8 lugares'],
    'EGO': ['Vaidade', 'Eu mesmo, no freudês'],
    'OBA': ['Que legal!', 'Vibração de quem ganhou'],
    'ABA': ['Borda do chapéu', 'Mulher do Boi (folcl.)'],
    'LOG': ['Histórico de sistema', 'Diário de eventos'],
    'VIL': ['Mesquinho', 'Adjetivo do antagonista'],
    'UVA': ['Fruta da videira', 'Bago do parreiral'],
    'VIR': ['Chegar ao falante', 'Aproximar-se'],
    'RUM': ['Cachaça do Caribe', 'Destilado da cana'],
    'BOI': ['Macho do gado', 'Animal que puxa o carro de ___'],
    'TAB': ['Janela do navegador', 'Tecla do teclado'],
    'TER': ['Possuir algo', 'Verbo do haver'],
    'FIM': ['Encerramento', 'O ___ do filme'],
    'GOL': ['Vibração na arquibancada', 'Bola na rede'],
    'PAZ': ['Sem guerra', 'Pomba branca simboliza'],
    'PRO': ['A favor', 'Atleta de elite (red.)'],
    'FLU': ['Tricolor das Laranjeiras', 'Maracanã: Vasco vs ___'],
    'LIS': ['Flor heráldica francesa', 'Capital de Portugal: ___boa'],
    'VAI': ['Sai daqui!', 'Verbo ir, 3ª pessoa'],
    'RIA': ['Dê risada', 'Estuário entre montanhas'],
    'PUB': ['Bar britânico', 'Onde se toma cerveja em Londres'],
    'SEM': ['Falta de algo', 'Privado de'],
    'LEI': ['Norma do código', 'Aprovada pelo Congresso'],
    'ZEN': ['Tranquilo, sereno', 'Budismo japonês'],
    'FOZ': ['Embocadura de rio', 'Cidade do Iguaçu'],
    'REI': ['Realeza masculina', 'Carta de baralho'],
    'LUA': ['Cheia, nova ou minguante', 'Onde Armstrong pisou'],
    'VEU': ['Da noiva', 'Coberta semi-transparente'],
    'BUG': ['Erro de programação', 'Inseto (ingl.)'],
    'REU': ['Quem responde processo', 'Acusado'],
    'MOR': ['Superlativo arcaico', 'O ___, em modos antigos'],
    'GEL': ['Cabelo: ___ fixador', 'Pasta viscosa'],
    'FAX': ['Tecnologia anos 90', 'Documento por linha telefônica'],
    'NAO': ['Discordância', 'Negativa simples'],
    'PSI': ['Caráter Ψ grego', 'Símbolo da mente humana'],
    'CAO': ['Melhor amigo do homem', 'Late ao estranho'],
    'MAO': ['5 dedos no ___', 'Aperto de ___'],
    'UAU': ['Que demais!', 'Reação de espanto positivo'],
    'TRI': ['Três campeonatos seguidos', 'Prefixo do número 3'],
    'CEM': ['Centena', 'Nota em prova ideal'],
    'NEO': ['Personagem do filme com Trinity', 'Prefixo: novo'],
    'SAX': ['Coltrane tocava', 'Madeira ou metal de jazz'],
    'CLA': ['Tribo familiar', 'Família Highlander'],
    'BIO': ['Vida (pref.)', 'Diversidade ___lógica'],
    'DUO': ['Casal musical', 'Dois cantando juntos'],
    'PUS': ['Sai do machucado', 'Líquido amarelado'],
    'TIA': ['Avó do primo', 'Parente feminina'],
    'BIT': ['0 ou 1', 'Menor unidade digital'],
    'VOZ': ['Cordas vocais', 'Solo do cantor'],
    'CHI': ['Energia oriental', 'Tai ___ chuan'],
    'JUS': ['Fazer ___ ao mérito', 'Direito (lat.)'],
    'POR': ['Mediante', 'Devido a'],
    'SEN': ['Aforismo, máxima', 'Casa legislativa (sigla)'],
    'TIO': ['Avô do primo', 'Parente masculino'],
    'MAL': ['Doença', 'Antônimo de bem'],
    'HOT': ['Picante (ingl.)', 'Quente em inglês'],
    'SIM': ['Concorda?', 'Resposta afirmativa'],
    'ZOO': ['Lugar de bichos', 'Onde ver leão e elefante'],
    'HIT': ['Top das paradas', 'Música em alta'],
    'PAO': ['Sai da padaria', 'Francês ou de queijo'],
    'DOI': ['Está doendo!', 'Causa sofrimento'],

    # ─── 4 letras (80 palavras) ──────────────────────────────────────
    'ORAL': ['Pela boca', 'Prova falada'],
    'AMOR': ['Sentimento profundo', 'Cupido inspira'],
    'ANAL': ['Reto, anatômico', 'Adjetivo do ânus'],
    'AZAR': ['Falta de sorte', 'Galinha preta'],
    'UVAS': ['Cachos de fruta', 'Bagos do parreiral'],
    'IRIS': ['Parte colorida do olho', 'Flor lilás de jardim'],
    'ARES': ['Climas, atmosferas', 'Deus grego da guerra'],
    'ORLA': ['Calçadão da praia', 'Margem do mar'],
    'ECOA': ['Reverbera', 'Som propaga em caverna'],
    'ANTE': ['Em frente a', 'Prefixo: que precede'],
    'RARO': ['Pouco frequente', 'Difícil de achar'],
    'TEOR': ['Quantidade contida', 'Conteúdo, essência'],
    'ACRE': ['Sabor azedo', 'Fronteira com Bolívia'],
    'ELBA': ['Ilha de exílio de Napoleão', 'Cantora ___ Ramalho'],
    'AURA': ['Energia do corpo', 'Halo místico'],
    'LACO': ['Nó decorativo', 'Fita amarrada'],
    'ELSA': ['Princesa de Frozen', 'Soltar a voz: ___ de Anna'],
    'LEAO': ['Rei da selva', 'Signo de fogo (jul-ago)'],
    'COLO': ['Onde a mãe acalma o nenê', 'Regaço'],
    'ASMA': ['Bombinha alivia', 'Falta de ar crônica'],
    'PURA': ['Sem mistura', 'Imaculada'],
    'TREM': ['Sai da estação', 'Em Minas: "esse ___ aí"'],
    'SORO': ['No braço, intravenoso', 'Líquido leitoso'],
    'MARE': ['Sobe e desce do oceano', 'Atrai a Lua'],
    'SUOR': ['Pinga da testa', 'Líquido do exercício'],
    'LAVA': ['Magma do vulcão', 'Verbo no presente: ___ a louça'],
    'SAIA': ['Roupa feminina', 'Verbo sair: 3ª pessoa'],
    'SINO': ['Bate na igreja', 'Toca dlim-dlim'],
    'REIS': ['Plural de monarca', 'Tres ___ Magos'],
    'ARMA': ['Espada ou pistola', 'Instrumento de combate'],
    'LOJA': ['Onde se compra', 'Ponto comercial'],
    'ODIO': ['Antônimo de amor', 'Rancor profundo'],
    'ARCA': ['Baú antigo', 'Salvou os animais do dilúvio'],
    'PNEU': ['Borracha do carro', 'Encheu, está bom'],
    'ROXO': ['Cor do açaí', 'Mistura azul e vermelho'],
    'LEMA': ['Frase de campanha', 'Slogan'],
    'LAPA': ['Bairro do Rio', 'Pedra grande'],
    'DOSE': ['Medida de remédio', 'Bebida única'],
    'LIRA': ['Velha moeda italiana', 'Instrumento dos gregos'],
    'CASA': ['Lugar onde se mora', 'Une os noivos'],
    'PIPA': ['Voa no céu com vento', 'Tonel de vinho'],
    'OSSO': ['Esqueleto', 'Cachorro adora'],
    'TEAR': ['Faz tecido', 'Máquina manual antiga'],
    'LOBO': ['Uiva pra lua', 'Personagem mau dos contos'],
    'VASO': ['Onde fica a planta', 'Recipiente decorativo'],
    'DANO': ['Estrago, prejuízo', 'Multa e ___ moral'],
    'GALA': ['Festa elegante', 'Vestido de baile'],
    'MALA': ['Bagagem de viagem', 'Pessoa chata (gíria)'],
    'VALE': ['Depressão entre montes', 'Ticket alimentação'],
    'FORO': ['Tribunal', 'Cidade do interior (lat.)'],
    'DONA': ['Senhora', 'Proprietária'],
    'ROLO': ['Confusão (gíria)', 'Cilindro'],
    'EURO': ['Moeda da UE', 'Símbolo €'],
    'CEPA': ['Tronco da videira', 'Variedade de uva'],
    'ANNA': ['Personagem de Frozen', 'Karenina, da literatura'],
    'LIMA': ['Capital do Peru', 'Lixa de unha'],
    'ENTE': ['Indivíduo, ser', 'Membro da família'],
    'PERU': ['País dos Andes', 'Ave do Natal'],
    'CAOS': ['Bagunça generalizada', 'Desordem total'],
    'AGIL': ['Veloz e flexível', 'Ginasta é ___'],
    'INOX': ['Talher resistente', 'Aço da pia'],
    'FLOR': ['Pétalas e perfume', 'Rosa, lírio, margarida'],
    'BALE': ['Sapatilhas e tutus', 'Dança clássica'],
    'ONDA': ['Surfe ___', 'Mexicana no estádio'],
    'NEON': ['Letreiro luminoso', 'Gás nobre amarelo'],
    'LEAL': ['Fiel ao compromisso', 'Cachorro é o melhor exemplo'],
    'RICA': ['Cheia de dinheiro', 'Próspera'],
    'FOME': ['Estômago vazio', 'Vontade de comer'],
    'ROTA': ['Caminho traçado', 'GPS calcula'],
    'CAGE': ['Nicolas, o ator', 'Jaula em inglês'],
    'MAXI': ['Tamanho grande', 'Saia ___ longa'],
    'SAPO': ['Anfíbio que coaxa', 'Apaixonado virou rei'],
    'FIOS': ['Cabelos', 'Linhas longas'],
    'ALCA': ['Mira da arma', 'Faixa da bolsa'],
    'DOIS': ['Número 2', 'Par de algo'],
    'AGRO': ['Setor rural', 'É pop'],
    'LONA': ['Cobre carga de caminhão', 'Tecido grosso impermeável'],
    'FITA': ['VHS, K7', 'Cassete'],
    'LATO': ['Amplo, vasto', 'Senso ___: significado geral'],
    'FIEL': ['Quem segue à risca', 'Devoto religioso'],

    # ─── 5 letras (41 palavras) ──────────────────────────────────────
    'OSSOS': ['Estrutura corporal', 'Cachorro guarda no quintal'],
    'ACASO': ['Coincidência', 'Sorte, sem planejar'],
    'ARENA': ['Praça de touros', 'Estádio de futebol moderno'],
    'ALAMO': ['Choupo', 'Batalha do Texas (1836)'],
    'ARROZ': ['Branco ou integral', 'Acompanha o feijão'],
    'COLAR': ['Pendurado no pescoço', 'Trapacear na prova'],
    'OPALA': ['Pedra preciosa iridescente', 'Sedan da Chevrolet'],
    'ARIEL': ['Sereia da Disney', 'Marca de sabão em pó'],
    'MAMAE': ['Carinho de mãe', 'Dia das ___ é em maio'],
    'SABOR': ['Doce, salgado, amargo', 'Gosto na boca'],
    'TORRE': ['Eiffel em Paris', 'Pisa famosa por inclinada'],
    'RIMAR': ['Compor versos', 'Combinar sons no fim'],
    'ARABE': ['Língua semítica', 'Da Arábia'],
    'IDOSO': ['3ª idade', 'Avô na cadeira de balanço'],
    'AMADA': ['Querida do coração', 'Bem-querida'],
    'REGRA': ['Norma do jogo', 'Princípio a seguir'],
    'OPERA': ['Espetáculo cantado', 'Cirurgia: "vou ___ você"'],
    'AEREO': ['Distraído', 'Voo de avião'],
    'SALAO': ['Onde corta cabelo', 'Festa em ___ social'],
    'MAIOR': ['Mais grande', 'Adulto, não menor'],
    'ISAAC': ['Newton, da gravidade', 'Filho de Abraão'],
    'ALLEN': ['Woody, cineasta', 'Edgar ___ Poe'],
    'CANAL': ['TV: ___ aberto', 'Curso d\'água artificial'],
    'RIVAL': ['Concorrente', 'Adversário direto'],
    'CORAL': ['Bicho do recife', 'Coro de cantores'],
    'APELO': ['Pedido emocional', 'Recurso jurídico'],
    'OSCAR': ['Estatueta de Hollywood', 'Niemeyer, arquiteto'],
    'CLARO': ['De luz boa', 'Que sim!'],
    'SAMBA': ['Ritmo do Carnaval carioca', 'Mangueira é escola de ___'],
    'USINA': ['Fábrica grande', 'De açúcar ou hidrelétrica'],
    'ATIVO': ['Em ação', 'Bem da empresa (contab.)'],
    'MOVEL': ['Cama, mesa, cadeira', 'Telefone celular antigo'],
    'ISCAS': ['Atrai o peixe', 'Pratico carne de fígado'],
    'RITMO': ['Cadência da música', 'Bate, bate'],
    'FALSO': ['Não autêntico', 'Imitação'],
    'ORFEU': ['Mito grego: lira', 'Negro, do filme de Carnaval'],
    'LOIRA': ['Cabelo claro', 'Cerveja: chope ___'],
    'SOLAR': ['Energia ___ fotovoltaica', 'Da casa-grande do engenho'],
    'ICONE': ['Símbolo cultural', 'Pequena imagem na tela'],
    'ADAMS': ['Família Addams', 'Bryan, cantor canadense'],
    'BOLAS': ['Esferas pra jogar', 'Plural de bolinha'],

    # ─── 6 letras (24 palavras) ──────────────────────────────────────
    'AMARGA': ['Sem doçura', 'Cerveja IPA é assim'],
    'ALCOOL': ['Etanol', 'Combustível ou bebida'],
    'ARROIO': ['Riacho pequeno', 'Curso d\'água gaúcho'],
    'AMADOR': ['Quem ama', 'Não-profissional'],
    'APOIAR': ['Dar suporte', 'Sustentar moralmente'],
    'PRATAS': ['Metais nobres', 'Plural de moeda'],
    'ACUCAR': ['Adoça o café', 'Pão de ___ no Rio'],
    'AGRAVO': ['Piora', 'Recurso jurídico'],
    'LAZARO': ['Ressuscitado por Jesus', 'Doente da Bíblia'],
    'CRIADA': ['Empregada doméstica', 'Feita, gerada'],
    'ROUPAS': ['Vestuário', 'Saem do guarda-roupa'],
    'ALEMAO': ['Da Alemanha', 'Pastor ___, raça canina'],
    'PANICO': ['Susto grande', 'Programa da TV'],
    'GLORIA': ['Honra extrema', 'Bairro do Rio'],
    'BOLETO': ['Pagamento bancário', 'Vence todo dia 10'],
    'GRAMAS': ['Unidades de massa', 'Plural de planta rasteira'],
    'LARSON': ['Brie, atriz', 'Sobrenome ianque'],
    'ALMOCO': ['Refeição do meio-dia', 'Hora do bandejão'],
    'APOSTA': ['Jogo de prognóstico', 'Bilhete da Mega-Sena'],
    'CAMADA': ['Estrato', 'Nível social'],
    'TORRES': ['Edifícios verticais', 'Plural da Eiffel'],
    'MARCAR': ['Pôr marca', 'Fazer ___ um gol'],
    'PARADA': ['Pausa no caminho', 'Coisa difícil (gíria)'],
    'ACERCA': ['A respeito de', 'Sobre o assunto de'],
}


def get_alt_clues():
    return dict(ALT_CLUES)
