"""
Banco de palavras em português para criptograma e palavras cruzadas.
Todas as palavras usam apenas A-Z (sem acentos).
Organizado por tamanho para garantir boa cobertura em cada dificuldade.
"""

import random

WORDS = [
    # ═══════════════ 4 letras ═══════════════
    {"word": "FLOR",  "clue": "Parte reprodutiva das plantas"},
    {"word": "MESA",  "clue": "Móvel com tampo para apoio"},
    {"word": "AMOR",  "clue": "Sentimento profundo de afeto"},
    {"word": "TREM",  "clue": "Veículo que circula sobre trilhos"},
    {"word": "MAPA",  "clue": "Representação geográfica de um território"},
    {"word": "PATO",  "clue": "Ave aquática de bico achatado"},
    {"word": "LOBO",  "clue": "Canídeo selvagem carnívoro"},
    {"word": "SAPO",  "clue": "Anfíbio de pele verrugosa"},
    {"word": "ILHA",  "clue": "Porção de terra cercada de água"},
    {"word": "OURO",  "clue": "Metal precioso de cor amarela"},
    {"word": "LEAO",  "clue": "Grande felino africano, rei da selva"},
    {"word": "SINO",  "clue": "Instrumento de bronze que tange"},
    {"word": "CASA",  "clue": "Edificação usada como moradia"},
    {"word": "SOPA",  "clue": "Alimento líquido servido quente"},
    {"word": "VILA",  "clue": "Pequena aglomeração urbana"},
    {"word": "CABO",  "clue": "Parte estreita de terra no mar"},
    {"word": "UVAS",  "clue": "Frutas da videira, matéria-prima do vinho"},
    {"word": "DEDO",  "clue": "Extremidade da mão"},

    # ═══════════════ 5 letras ═══════════════
    {"word": "SAMBA", "clue": "Ritmo e dança típica brasileira"},
    {"word": "NUVEM", "clue": "Massa de vapor d'água no céu"},
    {"word": "CHUVA", "clue": "Precipitação de água da atmosfera"},
    {"word": "VENTO", "clue": "Movimento natural do ar"},
    {"word": "PEIXE", "clue": "Vertebrado aquático com brânquias"},
    {"word": "CORAL", "clue": "Estrutura formada por animais marinhos"},
    {"word": "PORTA", "clue": "Abertura móvel para entrar em ambiente"},
    {"word": "PAPEL", "clue": "Material feito para escrever"},
    {"word": "LIVRO", "clue": "Obra impressa com páginas encadernadas"},
    {"word": "VERAO", "clue": "Estação do ano mais quente"},
    {"word": "ARROZ", "clue": "Cereal tradicional no prato brasileiro"},
    {"word": "VOLEI", "clue": "Esporte disputado sobre uma rede"},
    {"word": "MUSEU", "clue": "Local que preserva acervo histórico"},
    {"word": "TEMPO", "clue": "Medida da duração dos eventos"},
    {"word": "BANCO", "clue": "Instituição financeira"},
    {"word": "HOTEL", "clue": "Estabelecimento de hospedagem"},
    {"word": "PRAIA", "clue": "Faixa de areia à beira do mar"},
    {"word": "CARRO", "clue": "Veículo automotor de quatro rodas"},
    {"word": "POEMA", "clue": "Composição literária em versos"},
    {"word": "BEIJO", "clue": "Demonstração de carinho com os lábios"},
    {"word": "BARCO", "clue": "Embarcação de pequeno porte"},
    {"word": "PONTE", "clue": "Construção que liga duas margens"},
    {"word": "GRUPO", "clue": "Conjunto organizado de pessoas"},
    {"word": "IDEIA", "clue": "Pensamento, noção"},
    {"word": "LETRA", "clue": "Cada um dos sinais do alfabeto"},
    {"word": "ROSAS", "clue": "Flores tradicionalmente associadas ao amor"},
    {"word": "SALAO", "clue": "Grande cômodo ou sala de recepção"},
    {"word": "NARIZ", "clue": "Órgão do olfato no rosto"},
    {"word": "FRUTA", "clue": "Alimento doce produzido por árvores"},
    {"word": "PEDRA", "clue": "Fragmento sólido de rocha"},
    {"word": "RADIO", "clue": "Aparelho que capta ondas sonoras"},

    # ═══════════════ 6 letras ═══════════════
    {"word": "BRASIL",  "clue": "Maior país da América do Sul"},
    {"word": "OCEANO",  "clue": "Grande massa de água salgada"},
    {"word": "ANIMAL",  "clue": "Ser vivo do reino animal"},
    {"word": "ESCOLA",  "clue": "Instituição de ensino"},
    {"word": "CIDADE",  "clue": "Grande conjunto urbano"},
    {"word": "JANELA",  "clue": "Abertura na parede para luz e ar"},
    {"word": "CANELA",  "clue": "Especiaria aromática em pau ou pó"},
    {"word": "ALFACE",  "clue": "Folha verde muito usada em saladas"},
    {"word": "BANANA",  "clue": "Fruta tropical amarela curvada"},
    {"word": "TOMATE",  "clue": "Fruta vermelha usada como legume"},
    {"word": "BATATA",  "clue": "Tubérculo muito consumido no mundo"},
    {"word": "FEIJAO",  "clue": "Leguminosa base da culinária brasileira"},
    {"word": "GAVIAO",  "clue": "Ave de rapina"},
    {"word": "ACUCAR",  "clue": "Substância doce da cana"},
    {"word": "ARVORE",  "clue": "Planta de grande porte com tronco lenhoso"},
    {"word": "POESIA",  "clue": "Arte da palavra em versos"},
    {"word": "CINEMA",  "clue": "Indústria dos filmes"},
    {"word": "TEATRO",  "clue": "Arte da representação ao vivo"},
    {"word": "JARDIM",  "clue": "Espaço cultivado com plantas"},
    {"word": "MUSICA",  "clue": "Arte de combinar sons harmonicamente"},
    {"word": "NUMERO",  "clue": "Elemento matemático fundamental"},
    {"word": "ONIBUS",  "clue": "Veículo de transporte coletivo"},
    {"word": "AVIAO",   "clue": "Aeronave motorizada (5 letras na verdade)"},
    {"word": "ORELHA",  "clue": "Órgão auditivo externo"},
    {"word": "PANELA",  "clue": "Utensílio de cozinha"},
    {"word": "ALMOCO",  "clue": "Refeição do meio-dia"},
    {"word": "CORPOS",  "clue": "Organismos físicos"},
    {"word": "HUMANO",  "clue": "Pertencente ao Homo sapiens"},
    {"word": "SAPATO",  "clue": "Calçado fechado de sola rígida"},
    {"word": "ESPADA",  "clue": "Arma branca longa medieval"},
    {"word": "CAVALO",  "clue": "Equino usado como montaria"},
    {"word": "RAINHA",  "clue": "Consorte ou soberana de reino"},
    {"word": "MINUTO",  "clue": "60 segundos"},
    {"word": "QUARTO",  "clue": "Cômodo onde se dorme"},
    {"word": "ESCOVA",  "clue": "Utensílio com cerdas"},
    {"word": "DANCAR",  "clue": "Mover-se ao ritmo da música"},
    {"word": "JUSTICA", "clue": "Virtude de tratar com equidade"},
    {"word": "DANCA",   "clue": "Arte de se mover ao ritmo (5 letras)"},

    # ═══════════════ 7 letras ═══════════════
    {"word": "PLANETA", "clue": "Corpo celeste que orbita uma estrela"},
    {"word": "ESTRELA", "clue": "Corpo celeste luminoso"},
    {"word": "LARANJA", "clue": "Fruta cítrica de cor alaranjada"},
    {"word": "CENOURA", "clue": "Raiz alaranjada rica em vitamina A"},
    {"word": "ABACAXI", "clue": "Fruta tropical espinhosa"},
    {"word": "JANEIRO", "clue": "Primeiro mês do ano"},
    {"word": "INVERNO", "clue": "Estação mais fria do ano"},
    {"word": "PINTURA", "clue": "Arte de criar imagens com tinta"},
    {"word": "ROMANCE", "clue": "Gênero narrativo em prosa"},
    {"word": "DESENHO", "clue": "Representação em linhas"},
    {"word": "FORMIGA", "clue": "Pequeno inseto social"},
    {"word": "SEMENTE", "clue": "Origem de uma nova planta"},
    {"word": "GARAGEM", "clue": "Local para guardar veículos"},
    {"word": "REVOLTA", "clue": "Insurreição popular"},
    {"word": "ARTESAO", "clue": "Profissional de trabalhos manuais"},
    {"word": "LAGOSTA", "clue": "Crustáceo marinho nobre"},
    {"word": "TELHADO", "clue": "Cobertura superior da casa"},
    {"word": "TORNEIO", "clue": "Competição esportiva"},
    {"word": "TURISMO", "clue": "Prática de viajar por lazer"},
    {"word": "EMPREGO", "clue": "Ocupação remunerada"},
    {"word": "VERDADE", "clue": "Oposto da mentira"},
    {"word": "PADEIRO", "clue": "Profissional que faz pães"},
    {"word": "JORNADA", "clue": "Período de trabalho diário"},
    {"word": "BATALHA", "clue": "Grande combate militar"},
    {"word": "PEQUENO", "clue": "De dimensão reduzida"},
    {"word": "MEDALHA", "clue": "Premiação metálica esportiva"},
    {"word": "MUDANCA", "clue": "Alteração ou transformação"},
    {"word": "QUEIJOS", "clue": "Alimentos feitos de leite"},
    {"word": "TEXTURA", "clue": "Característica tátil da superfície"},
    {"word": "AZULEJO", "clue": "Placa cerâmica decorativa"},
    {"word": "JOELHOS", "clue": "Articulações entre coxa e canela"},
    {"word": "FAVORES", "clue": "Atos de benevolência"},
    {"word": "AVENTAL", "clue": "Peça que protege roupas ao cozinhar"},
    {"word": "MAQUINA", "clue": "Equipamento mecânico"},
    {"word": "VINAGRE", "clue": "Líquido ácido usado em saladas"},
    {"word": "OREGANO", "clue": "Erva aromática de pizza"},
    {"word": "MACHADO", "clue": "Ferramenta para cortar madeira"},
    {"word": "MADEIRA", "clue": "Material obtido das árvores"},
    {"word": "MARTELO", "clue": "Ferramenta para bater pregos"},
    {"word": "CAMINHO", "clue": "Via de passagem"},
    {"word": "DOMINGO", "clue": "Sétimo dia da semana"},
    {"word": "FAZENDA", "clue": "Grande propriedade rural"},
    {"word": "CASCATA", "clue": "Queda d'água pequena"},
    {"word": "ESCRITA", "clue": "Ato de escrever"},
    {"word": "RETRATO", "clue": "Imagem de uma pessoa"},
    {"word": "TECIDOS", "clue": "Materiais têxteis"},
    {"word": "TRIUNFO", "clue": "Vitória gloriosa"},
    {"word": "VELEIRO", "clue": "Embarcação à vela"},
    {"word": "VINHEDO", "clue": "Plantação de uvas"},
    {"word": "VOCACAO", "clue": "Chamado ou inclinação pessoal"},
    {"word": "CABELOS", "clue": "Fios que cobrem a cabeça"},
    {"word": "ENCANTO", "clue": "Fascínio despertado"},
    {"word": "INIMIGO", "clue": "Adversário declarado"},
    {"word": "INSETOS", "clue": "Pequenos artrópodes"},
    {"word": "XICARAS", "clue": "Vasilhas pequenas para café"},
    {"word": "RAQUETE", "clue": "Instrumento usado no tênis"},
    {"word": "RECORDE", "clue": "Marca atingida, feito excepcional"},
    {"word": "TIJOLOS", "clue": "Blocos cerâmicos de construção"},
    {"word": "VIDEIRA", "clue": "Planta que produz uva"},
    {"word": "PERFUME", "clue": "Essência aromática"},
    {"word": "ORVALHO", "clue": "Umidade matinal das folhas"},
    {"word": "SEGREDO", "clue": "Informação oculta"},
    {"word": "PALHACO", "clue": "Artista circense engraçado"},
    {"word": "GALINHA", "clue": "Ave doméstica ovípara"},
    {"word": "DECIMAL", "clue": "Sistema numérico de base dez"},
    {"word": "HERANCA", "clue": "Bens legados a alguém"},
    {"word": "HIGIENE", "clue": "Prática de limpeza corporal"},
    {"word": "NUBLADO", "clue": "Céu com muitas nuvens"},
    {"word": "OFICIAL", "clue": "Que tem caráter formal"},
    {"word": "RISADAS", "clue": "Expressões sonoras de alegria"},
    {"word": "ANIMAIS", "clue": "Seres do reino animal"},
    {"word": "RECEITA", "clue": "Instrução para preparar prato"},
    {"word": "GERENTE", "clue": "Profissional que administra negócio"},
    {"word": "CHINELO", "clue": "Calçado aberto de uso caseiro"},
    {"word": "CABANA",  "clue": "Pequena casa rústica (6 letras)"},
    {"word": "NOTURNO", "clue": "Relativo à noite"},
    {"word": "VIAGENS", "clue": "Deslocamentos a outros lugares"},
    {"word": "FAMILIA", "clue": "Conjunto de parentes próximos"},
    {"word": "LEITURA", "clue": "Ato de ler"},
    {"word": "COMIDAS", "clue": "Alimentos diversos"},
    {"word": "SAUDADE", "clue": "Sentimento brasileiro de falta"},
    {"word": "MARINHO", "clue": "Relativo ao mar"},
    {"word": "OCULOS",  "clue": "Acessório para correção visual (6)"},
    {"word": "TROPICO", "clue": "Paralelo terrestre em região quente"},

    # ═══════════════ 8 letras ═══════════════
    {"word": "FLORESTA", "clue": "Grande extensão de árvores"},
    {"word": "MONTANHA", "clue": "Grande elevação natural"},
    {"word": "CARNAVAL", "clue": "Festa brasileira mais famosa"},
    {"word": "ELEFANTE", "clue": "Maior mamífero terrestre"},
    {"word": "HOSPITAL", "clue": "Instituição de saúde"},
    {"word": "CAPOEIRA", "clue": "Arte marcial brasileira com música"},
    {"word": "TELEFONE", "clue": "Aparelho de comunicação à distância"},
    {"word": "INTERNET", "clue": "Rede mundial de computadores"},
    {"word": "PROGRAMA", "clue": "Conjunto de instruções de computador"},
    {"word": "SERVIDOR", "clue": "Computador que oferece serviços em rede"},
    {"word": "BISCOITO", "clue": "Doce assado pequeno"},
    {"word": "CAMINHAO", "clue": "Veículo de carga pesada"},
    {"word": "FANTASIA", "clue": "Imaginação criativa"},
    {"word": "CACHORRO", "clue": "Mamífero doméstico, melhor amigo do homem"},
    {"word": "PALMEIRA", "clue": "Árvore tropical sem galhos"},
    {"word": "RESPOSTA", "clue": "Retorno a uma pergunta"},
    {"word": "BICICLETA","clue": "Veículo de duas rodas movido a pedal (9)"},
    {"word": "MANDIOCA", "clue": "Raiz típica da culinária brasileira"},
    {"word": "TECLADO",  "clue": "Dispositivo de entrada com teclas (7)"},
    {"word": "ACIDENTE", "clue": "Ocorrência imprevista e indesejada"},
    {"word": "ALEMANHA", "clue": "País da Europa central"},
    {"word": "ALFINETE", "clue": "Pequeno objeto pontiagudo"},
    {"word": "ARMADURA", "clue": "Proteção metálica medieval"},
    {"word": "AVESTRUZ", "clue": "Maior ave do mundo, não voa"},
    {"word": "BANHEIRA", "clue": "Recipiente para banho"},
    {"word": "BANHEIRO", "clue": "Cômodo com vaso sanitário"},
    {"word": "BERIMBAU", "clue": "Instrumento da capoeira"},
    {"word": "CAMISETA", "clue": "Peça de vestuário superior casual"},
    {"word": "CAMPANHA", "clue": "Ação organizada com fim específico"},
    {"word": "CAPITULO", "clue": "Divisão de um livro"},
    {"word": "CAPRICHO", "clue": "Esmero no trabalho"},
    {"word": "CATEDRAL", "clue": "Grande templo cristão"},
    {"word": "COQUETEL", "clue": "Bebida mista com várias doses"},
    {"word": "CORRIDAS", "clue": "Competições de velocidade"},
    {"word": "CUIDADOS", "clue": "Zelo e atenção dispensada"},
    {"word": "DENTISTA", "clue": "Profissional que cuida dos dentes"},
    {"word": "DESCANSO", "clue": "Período de repouso"},
    {"word": "DESERTOS", "clue": "Regiões áridas e desoladas"},
    {"word": "DINHEIRO", "clue": "Meio de pagamento"},
    {"word": "DISCURSO", "clue": "Fala pública organizada"},
    {"word": "EDUCACAO", "clue": "Formação intelectual"},
    {"word": "ELETRICO", "clue": "Movido a eletricidade"},
    {"word": "ESCOLHAS", "clue": "Alternativas selecionadas"},
    {"word": "ESPECIAL", "clue": "Fora do comum, único"},
    {"word": "FAMILIAS", "clue": "Grupos de parentes"},
    {"word": "FAROESTE", "clue": "Gênero cinematográfico do velho oeste"},
    {"word": "FOGUEIRA", "clue": "Pilha de lenha em chamas"},
    {"word": "FOLCLORE", "clue": "Cultura popular tradicional"},
    {"word": "GANHADOR", "clue": "Aquele que vence"},
    {"word": "GIGANTES", "clue": "Seres muito grandes"},
    {"word": "HARMONIA", "clue": "Combinação agradável"},
    {"word": "HEPATITE", "clue": "Inflamação do fígado"},
    {"word": "LEGENDAS", "clue": "Texto abaixo de imagens"},
    {"word": "MACARRAO", "clue": "Massa típica italiana"},
    {"word": "MARACUJA", "clue": "Fruta amarela azeda"},
    {"word": "MENSAGEM", "clue": "Comunicação transmitida"},
    {"word": "MINEIROS", "clue": "Habitantes de Minas Gerais"},
    {"word": "OBJETIVO", "clue": "Meta a ser alcançada"},
    {"word": "OPERADOR", "clue": "Quem opera uma máquina"},
    {"word": "OTIMISMO", "clue": "Visão positiva da vida"},
    {"word": "PANETONE", "clue": "Bolo natalino com frutas"},
    {"word": "PESCARIA", "clue": "Ato de pescar"},
    {"word": "PETROLEO", "clue": "Combustível fóssil líquido"},
    {"word": "PINGENTE", "clue": "Joia pendurada em fio"},
    {"word": "PIZZARIA", "clue": "Restaurante de pizzas"},
    {"word": "PRESIDIO", "clue": "Local de cumprimento de pena"},
    {"word": "RELIGIAO", "clue": "Conjunto de crenças espirituais"},
    {"word": "SANGRIAS", "clue": "Bebidas com vinho e frutas"},
    {"word": "SENTIDOS", "clue": "Faculdades perceptivas humanas"},
    {"word": "SIMPATIA", "clue": "Afinidade agradável"},
    {"word": "SINFONIA", "clue": "Grande composição orquestral"},
    {"word": "SURPRESA", "clue": "Acontecimento inesperado"},
    {"word": "TEMPORAL", "clue": "Chuva intensa com ventos"},
    {"word": "TRABALHO", "clue": "Atividade laboral"},
    {"word": "TRANSITO", "clue": "Circulação de veículos"},
    {"word": "TROPICOS", "clue": "Zonas climáticas quentes do globo"},
    {"word": "VITAMINA", "clue": "Nutriente essencial"},
    {"word": "LENTILHA", "clue": "Leguminosa pequena e achatada"},
    {"word": "RATAZANA", "clue": "Grande roedor urbano"},
    {"word": "VENTANIA", "clue": "Vento muito forte"},
    {"word": "SANDALIA", "clue": "Calçado aberto de verão"},
    {"word": "PERSIANA", "clue": "Cortina de lâminas horizontais"},
    {"word": "PIONEIRO", "clue": "Quem inicia algo novo"},
    {"word": "PLASTICO", "clue": "Material sintético versátil"},
    {"word": "PRESUNTO", "clue": "Embutido de porco curado"},
    {"word": "BARBEIRO", "clue": "Profissional que corta cabelos"},
    {"word": "CAPIVARA", "clue": "Maior roedor do mundo"},

    # ═══════════════ 9 letras ═══════════════
    {"word": "BORBOLETA",  "clue": "Inseto colorido, antes lagarta"},
    {"word": "LIBERDADE",  "clue": "Estado de quem não tem restrições"},
    {"word": "ESPERANCA",  "clue": "Sentimento de expectativa positiva"},
    {"word": "ESCULTURA",  "clue": "Arte de criar formas tridimensionais"},
    {"word": "ORQUESTRA",  "clue": "Grande grupo de músicos"},
    {"word": "CROCODILO",  "clue": "Réptil aquático de grande porte"},
    {"word": "TARTARUGA",  "clue": "Réptil com casco e vida longa"},
    {"word": "CASAMENTO",  "clue": "União matrimonial"},
    {"word": "LABIRINTO",  "clue": "Caminho complexo e confuso"},
    {"word": "MANDIBULA",  "clue": "Osso inferior do maxilar"},
    {"word": "SANDUICHE",  "clue": "Lanche com recheio entre pães"},
    {"word": "AERONAVES",  "clue": "Máquinas voadoras"},
    {"word": "ANDARILHO",  "clue": "Quem caminha sem destino fixo"},
    {"word": "ANDORINHA",  "clue": "Pequena ave migratória"},
    {"word": "ATMOSFERA",  "clue": "Camada gasosa que envolve a Terra"},
    {"word": "BOMBEIROS",  "clue": "Profissionais que combatem incêndios"},
    {"word": "CACHORROS",  "clue": "Mamíferos domésticos, canídeos"},
    {"word": "CARNAVAIS",  "clue": "Festas populares de fevereiro"},
    {"word": "CLASSICOS",  "clue": "Obras tradicionais e consagradas"},
    {"word": "DESAJUSTE",  "clue": "Falta de sintonia"},
    {"word": "DESPEDIDA",  "clue": "Ato de se afastar de alguém"},
    {"word": "DETALHADO",  "clue": "Feito com muitos detalhes"},
    {"word": "ELEFANTES",  "clue": "Grandes mamíferos africanos"},
    {"word": "EMBAIXADA",  "clue": "Representação diplomática"},
    {"word": "FERROVIAS",  "clue": "Linhas de transporte sobre trilhos"},
    {"word": "FORMATADO",  "clue": "Organizado em formato específico"},
    {"word": "GLADIADOR",  "clue": "Lutador da Roma Antiga"},
    {"word": "GUERREIRO",  "clue": "Combatente valoroso"},
    {"word": "HABITACAO",  "clue": "Local de moradia"},
    {"word": "HISTORIAS",  "clue": "Narrativas de fatos"},
    {"word": "HORIZONTE",  "clue": "Linha onde céu encontra a terra"},
    {"word": "IDEOLOGIA",  "clue": "Sistema de ideias políticas"},
    {"word": "ILUMINADA", "clue": "Com iluminação ou esclarecida"},
    {"word": "JACARANDA",  "clue": "Árvore brasileira de flores roxas"},
    {"word": "LAVADEIRA",  "clue": "Mulher que lava roupas"},
    {"word": "LIDERANCA",  "clue": "Capacidade de liderar pessoas"},
    {"word": "MASCARADO",  "clue": "Que usa máscara no rosto"},
    {"word": "METEORITO",  "clue": "Corpo celeste que atinge a Terra"},
    {"word": "MONARQUIA",  "clue": "Regime de governo com rei"},
    {"word": "MUNICIPAL",  "clue": "Relativo ao município"},
    {"word": "NATUREZAS", "clue": "Ambientes naturais variados"},
    {"word": "OFENDIDOS", "clue": "Que sofreram desrespeito"},
    {"word": "OPERACOES", "clue": "Intervenções ou processos"},
    {"word": "ORCAMENTO",  "clue": "Previsão de receitas e despesas"},
    {"word": "ORIGINAIS",  "clue": "Autênticos, não copiados"},
    {"word": "ORNAMENTO",  "clue": "Elemento decorativo"},
    {"word": "PANDEMIAS",  "clue": "Epidemias de alcance mundial"},
    {"word": "PANORAMAS",  "clue": "Vistas amplas de um lugar"},
    {"word": "PAPAGAIOS",  "clue": "Aves coloridas que imitam voz"},
    {"word": "PARTITURA",  "clue": "Folha com notação musical"},
    {"word": "PATAMARES",  "clue": "Níveis intermediários"},
    {"word": "PERIFERIA",  "clue": "Região afastada do centro"},
    {"word": "PERMITIDO",  "clue": "Que foi autorizado"},
    {"word": "PERSIANAS",  "clue": "Cortinas de lâminas"},
    {"word": "PRINCIPIO",  "clue": "Começo ou fundamento"},
    {"word": "PROCESSOS",  "clue": "Sequências de etapas"},
    {"word": "PROFESSOR",  "clue": "Profissional do ensino"},
    {"word": "PROMESSAS",  "clue": "Compromissos assumidos"},
    {"word": "PROTOCOLO",  "clue": "Normas formais de procedimento"},
    {"word": "RENOVACAO",  "clue": "Ato de deixar novo"},
    {"word": "REQUISITO",  "clue": "Condição necessária"},
    {"word": "RESULTADO",  "clue": "Conclusão ou consequência"},
    {"word": "SAMBISTAS",  "clue": "Artistas do samba"},
    {"word": "SATELITES",  "clue": "Corpos que orbitam planetas"},
    {"word": "SIMPATICO",  "clue": "Agradável no trato"},
    {"word": "SINDICATO",  "clue": "Associação de trabalhadores"},
    {"word": "SONHADORA",  "clue": "Que sonha demais"},
    {"word": "TERRESTRE",  "clue": "Relativo à Terra"},
    {"word": "TROVOADAS",  "clue": "Temporais com trovões"},
    {"word": "VAGABUNDO",  "clue": "Andarilho sem ocupação fixa"},
    {"word": "VITORIOSO",  "clue": "Que venceu"},
    {"word": "ASTRONOMO",  "clue": "Cientista dos corpos celestes"},
    {"word": "MAGISTRAL",  "clue": "Digno de um mestre"},
    {"word": "MATRIMONIO","clue": "Vínculo entre cônjuges (10)"},
    {"word": "PIRAMIDES",  "clue": "Monumentos egípcios famosos"},
    {"word": "SINFONIAS",  "clue": "Grandes composições musicais"},
    {"word": "CAPRICHOS",  "clue": "Desejos passageiros"},
    {"word": "MARACUJAS",  "clue": "Frutas amarelas azedas"},
    {"word": "SIGNIFICA",  "clue": "Quer dizer, denota"},
    {"word": "SINTETICO",  "clue": "Resumido ou artificial"},
    {"word": "TRADICOES",  "clue": "Costumes transmitidos"},
    {"word": "REMEDIOS",   "clue": "Medicamentos (8 letras)"},
    {"word": "ROUPAGENS",  "clue": "Vestimentas"},
    {"word": "BORRACHAS",  "clue": "Materiais elásticos para apagar"},

    # ═══════════════ 10 letras ═══════════════
    {"word": "COMPUTADOR",  "clue": "Máquina eletrônica de processar dados"},
    {"word": "MATEMATICA",  "clue": "Ciência dos números"},
    {"word": "ASTRONOMIA",  "clue": "Ciência dos corpos celestes"},
    {"word": "DEMOCRACIA",  "clue": "Sistema de governo pelo povo"},
    {"word": "BIBLIOTECA",  "clue": "Local com acervo de livros"},
    {"word": "ADRENALINA",  "clue": "Hormônio da excitação"},
    {"word": "ASSOCIACAO",  "clue": "União de pessoas por causa comum"},
    {"word": "ASTRONAUTA",  "clue": "Explorador do espaço"},
    {"word": "ATROPELADO",  "clue": "Atingido por veículo em movimento"},
    {"word": "AUTORIDADE",  "clue": "Pessoa com poder legítimo"},
    {"word": "BRASILEIRA",  "clue": "Natural do Brasil, feminino"},
    {"word": "BRINQUEDOS",  "clue": "Objetos para diversão infantil"},
    {"word": "CALENDARIO",  "clue": "Sistema organizado de datas"},
    {"word": "CARICATURA",  "clue": "Desenho com exagero humorístico"},
    {"word": "ENGENHARIA",  "clue": "Profissão da área técnica"},
    {"word": "ENTRETANTO",  "clue": "Conjunção de oposição (contudo)"},
    {"word": "ESCRITORIO",  "clue": "Local de trabalho administrativo"},
    {"word": "FELICIDADE",  "clue": "Estado de satisfação plena"},
    {"word": "FERRAMENTA",  "clue": "Instrumento de trabalho manual"},
    {"word": "FINALIDADE",  "clue": "Objetivo final"},
    {"word": "FORMULARIO",  "clue": "Documento para preenchimento"},
    {"word": "GARIMPEIRO",  "clue": "Quem busca ouro em rios"},
    {"word": "GUARDANAPO",  "clue": "Pano para limpar a boca"},
    {"word": "HIPOPOTAMO",  "clue": "Mamífero africano semi-aquático"},
    {"word": "HUMANIDADE",  "clue": "Conjunto dos seres humanos"},
    {"word": "JUSTICEIRO",  "clue": "Aquele que impõe justiça"},
    {"word": "LANCAMENTO",  "clue": "Ato de lançar ao mercado"},
    {"word": "LITERATURA",  "clue": "Arte da escrita"},
    {"word": "MONUMENTOS",  "clue": "Obras arquitetônicas memoráveis"},
    {"word": "PENSAMENTO",  "clue": "Atividade mental consciente"},
    {"word": "PERSONAGEM",  "clue": "Figura em obra de ficção"},
    {"word": "PLATAFORMA",  "clue": "Estrutura elevada horizontal"},
    {"word": "PRESIDENTE",  "clue": "Chefe máximo de instituição"},
    {"word": "QUILOMETRO",  "clue": "Unidade equivalente a mil metros"},
    {"word": "RACIOCINIO",  "clue": "Processo de pensar logicamente"},
    {"word": "REPERTORIO",  "clue": "Conjunto de obras conhecidas"},
    {"word": "REPORTAGEM",  "clue": "Trabalho jornalístico investigativo"},
    {"word": "ROTEIRISTA",  "clue": "Autor de roteiros"},
    {"word": "SECRETARIA",  "clue": "Órgão administrativo"},
    {"word": "SEMELHANCA",  "clue": "Qualidade do que é parecido"},
    {"word": "SUBMARINOS",  "clue": "Embarcações que navegam submersas"},
    {"word": "TENTACULOS",  "clue": "Braços de polvos e lulas"},
    {"word": "TESTEMUNHA",  "clue": "Quem presencia um fato"},
    {"word": "TIPOGRAFIA",  "clue": "Arte da impressão com tipos"},
    {"word": "TRADUTORES",  "clue": "Profissionais que vertem idiomas"},
    {"word": "TRIANGULOS",  "clue": "Figuras geométricas de 3 lados"},
    {"word": "URBANISTAS",  "clue": "Profissionais do planejamento urbano"},
    {"word": "VITALIDADE",  "clue": "Energia e força de vida"},
    {"word": "VITORIOSOS",  "clue": "Aqueles que venceram"},
    {"word": "ACADEMICOS",  "clue": "Relativos à academia"},
    {"word": "AGRICULTURA","clue": "Cultivo da terra (11)"},
    {"word": "APAIXONADO",  "clue": "Que sente paixão"},
    {"word": "ASSEGURADO",  "clue": "Que foi garantido"},
    {"word": "BANHEIRINHO","clue": "Pequeno banheiro (11)"},
    {"word": "CONHECIDAS",  "clue": "Famosas, já vistas"},
    {"word": "CONSTANTES",  "clue": "Que não mudam"},
    {"word": "DESCOBERTO",  "clue": "Revelado, sem cobertura"},
    {"word": "EVIDENCIAS",  "clue": "Provas claras"},
    {"word": "GENEROSOS",   "clue": "Generosos (9)"},
    {"word": "HELICOPTER", "clue": "Aeronave de rotor (11: HELICOPTERO)"},
    {"word": "IMPACTANTE",  "clue": "Que causa grande impressão"},
    {"word": "INVESTIGAR",  "clue": "Pesquisar a fundo"},
    {"word": "LONGAMENTE",  "clue": "Por muito tempo"},
    {"word": "MARAVILHAR", "clue": "Causar admiração"},
    {"word": "NOTORIEDADE","clue": "Fama reconhecida (11)"},
    {"word": "PANCARIADA",  "clue": "Grande quantidade de pancadas"},
    {"word": "PERSEGUIDO",  "clue": "Que vem sendo seguido"},
    {"word": "PROCURADOR",  "clue": "Quem atua em nome de outro"},
    {"word": "RESPONSAVEL","clue": "Que responde pelos atos (11)"},
    {"word": "SATISFEITOS", "clue": "Contentes (11)"},
    {"word": "ANIVERSARIO", "clue": "Comemoração anual do nascimento (11)"},
]


def _normalize_bank():
    """Remove duplicatas e garante só A-Z."""
    seen = set()
    unique = []
    for w in WORDS:
        word = w["word"].upper()
        if not word.isalpha() or not word.isascii():
            continue
        if len(word) != len(w["word"]):
            continue
        # Corrige o length indicado na lista: se disser "X letras" errado, ignora
        # (a verdade é len(word))
        if word in seen:
            continue
        seen.add(word)
        unique.append({"word": word, "clue": w["clue"]})
    return unique


_CACHE = _normalize_bank()


def get_word_list():
    """Retorna uma cópia embaralhada da lista de palavras."""
    result = _CACHE.copy()
    random.shuffle(result)
    return result
